namespace offsets
{
	namespace UEdGraphPin_Deprecated
	{
			constexpr auto PinName = 0x28; // Size: 16, Type: struct FString
			constexpr auto PinToolTip = 0x38; // Size: 16, Type: struct FString
			constexpr auto Direction = 0x48; // Size: 1, Type: enum class EEdGraphPinDirection
			constexpr auto PinType = 0x50; // Size: 88, Type: struct FEdGraphPinType
			constexpr auto DefaultValue = 0xa8; // Size: 16, Type: struct FString
			constexpr auto AutogeneratedDefaultValue = 0xb8; // Size: 16, Type: struct FString
			constexpr auto DefaultObject = 0xc8; // Size: 8, Type: struct UObject*
			constexpr auto DefaultTextValue = 0xd0; // Size: 24, Type: struct FText
			constexpr auto LinkedTo = 0xe8; // Size: 16, Type: struct TArray<struct UEdGraphPin_Deprecated*>
			constexpr auto SubPins = 0xf8; // Size: 16, Type: struct TArray<struct UEdGraphPin_Deprecated*>
			constexpr auto ParentPin = 0x108; // Size: 8, Type: struct UEdGraphPin_Deprecated*
			constexpr auto ReferencePassThroughConnection = 0x110; // Size: 8, Type: struct UEdGraphPin_Deprecated*
	}
} 
